package LEXER;

/**
 * Enum representing possible token types.
 */
public enum TokenType {
    MULTI_LINE_COMMENT,
    SINGLE_LINE_COMMENT,
    KEYWORD,
    BOOLEAN_CONSTANT,
    OPERATOR,
    FLOAT_CONSTANT,
    INT_CONSTANT,
    IDENTIFIER,
    INVALID_IDENTIFIER,
    STRING_CONSTANT,
    CHAR_CONSTANT,
    PUNCTUATION,
    NEWLINE,
    WHITESPACE,
    INVALID,
    END_MARKER
}