package LEXER;

public enum TokenType {
    KEYWORD,
    IDENTIFIER,
    INVALID_IDENTIFIER,
    OPERATOR,
    PUNCTUATION,
    STRING_CONSTANT,
    CHAR_CONSTANT,
    BOOLEAN_CONSTANT,
    INT_CONSTANT,
    FLOAT_CONSTANT,
    SINGLE_LINE_COMMENT,
    MULTI_LINE_COMMENT,
    WHITESPACE,
    NEWLINE,
    INVALID
}
